export const newsData = [
    {
        'id':1,
        'title':"MEA: PM Modi’s visit to Bhutan postponed due to bad weather",
        'image':"../../assets/images/samantha.png",
        'source':"Hindustan Times",
        "description":"Prime Minister Narendra Modi’s upcoming Bhutan visit has been postponed due to bad weather conditions, the Ministry of External Affairs said on Wednesday.The PM was scheduled to visit the neighbouring country on March 21-22. “Due to ongoing inclement weather conditions over Paro airport, it has been mutually decided to postpone the State visit of Prime Minister to Bhutan on 21-22 March 2024. New dates are being worked out by the two sides through diplomatic channels,” the MEA’s statement read.",
        "detail_description": `Prime Minister Narendra Modi’s upcoming Bhutan visit has been postponed due to bad weather conditions, the Ministry of External Affairs said on Wednesday.
        The PM was scheduled to visit the neighbouring country on March 21-22.
        “Due to ongoing inclement weather conditions over Paro airport, it has been mutually decided to postpone the State visit of Prime Minister to Bhutan on 21-22 March 2024. New dates are being worked out by the two sides through diplomatic channels,” the MEA’s statement read.`
    },
    {
        'id':2,
        'title':"Sadhguru undergoes emergency ‘brain surgery’, recovering: Isha Foundation",
        'image':"../../assets/images/samantha.png",
        'source':"Indian Express",
        "description":"Spiritual leader Sadhguru recently underwent a “brain surgery” and is currently recovering from the procedure, his organisation, Isha Foundation, said in a statement on Wednesday.   It said that the surgery was necessitated after a “life-threatening bleeding in his brain”. “A few days ago, Sadhguru underwent brain surgery after life-threatening bleeding in the brain. Sadhguru is recovering very well, and the team of doctors who performed the surgery say his condition is improving beyond expectations,” the Isha Foundation said in a post on X, quoting Apollo Hospitals’ Dr Vinit Suri.",
        "detail_description": `Spiritual leader Sadhguru recently underwent a “brain surgery” and is currently recovering from the procedure, his organisation, Isha Foundation, said in a statement on Wednesday.
        It said that the surgery was necessitated after a “life-threatening bleeding in his brain”.
        “A few days ago, Sadhguru underwent brain surgery after life-threatening bleeding in the brain. Sadhguru is recovering very well, and the team of doctors who performed the surgery say his condition is improving beyond expectations,” the Isha Foundation said in a post on X, quoting Apollo Hospitals’ Dr Vinit Suri.`
    },
    {
        'id':3,
        'title':"Katrina Kaif found Vicky Kaushal ‘khadoos’ for first 2 years of relationship, called him the ‘most unromantic gift giver’",
        'image':"../../assets/images/samantha.png",
        'source':"Times of India",
        "description":"Vicky Kaushal and Katrina Kaif got married after dating each other for a couple of years. And until they tied the knot, they never opened up about their relationship in front of the world. But ever since they declared their relationship, Vicky and Katrina like to share tidbits about their relationship which were unknown to their fans. In a recent interview, Vicky was asked if there are things that Katrina finds annoying about him and Vicky said that for the first two years of their relationship, she would call him ‘khadoos‘ (grumpy). Vicky shared that Katrina doesn’t appreciate his stubbornness. When asked if this is because he does not apologise first, Vicky said that he is “the first one to say sorry  but sometimes, I am stubborn, until I am convinced about something.” He then shared with a laugh, on No Filter Neha, that for the first two years of their relationship, she would call him “khadoos.” “She used to feel that my resting face is khadoos,” he said. Vicky also said that Katrina called him the “most unromantic gift giver,”  and when Neha asked him about the last given he had gotten for his wife, Vicky said, “Jewellery.”",
        "detail_description": `Vicky Kaushal and Katrina Kaif got married after dating each other for a couple of years. And until they tied the knot, they never opened up about their relationship in front of the world. But ever since they declared their relationship, Vicky and Katrina like to share tidbits about their relationship which were unknown to their fans. In a recent interview, Vicky was asked if there are things that Katrina finds annoying about him and Vicky said that for the first two years of their relationship, she would call him ‘khadoos‘ (grumpy).
        Vicky shared that Katrina doesn’t appreciate his stubbornness. When asked if this is because he does not apologise first, Vicky said that he is “the first one to say sorry  but sometimes, I am stubborn, until I am convinced about something.” He then shared with a laugh, on No Filter Neha, that for the first two years of their relationship, she would call him “khadoos.” “She used to feel that my resting face is khadoos,” he said. Vicky also said that Katrina called him the “most unromantic gift giver,”  and when Neha asked him about the last given he had gotten for his wife, Vicky said, “Jewellery.”`
    },
    {
        'id':4,
        'title':"SBI filed ‘false affidavit’, recorded electoral bond numbers ‘illegally’: Former finance secy Subhash Garg",
        'image':"../../assets/images/samantha.png",
        'source':"Indian Express",
        "description":"A day after the State Bank of India (SBI) provided all details of electoral bonds purchased and redeemed, including the alphanumeric codes of each bond that enabled donors to be matched with the recipients, former finance secretary Subhash Chandra Garg on Friday said the bank was not supposed to record the bond numbers and in doing so it had violated the anonymity promised to donors under the Electoral Bond Scheme, 2018. He also pointed out that the earlier affidavit filed by the bank on the matter was “ostensibly false”. The SBI had done something “completely unlawful and unexpected”, Garg told The Indian Express. By recording the alphanumeric codes of the bonds sold to donors and encashed by political parties, the bank had hit at the basic feature of the scheme that was brought in by the government in 2018 to enable anonymous political donations, he said. “The SBI said in its first affidavit that the information of donors and parties was kept in physical form in two silos and that it would take three months to match. But subsequent events have shown that they recorded the information in a digital form. Their first affidavit appears to be motivated by the desire to push the disclosure of the data beyond the Lok Sabha elections. Why did they file the ostensibly false affidavit,” asked Garg.",
        "detail_description": `A day after the State Bank of India (SBI) provided all details of electoral bonds purchased and redeemed, including the alphanumeric codes of each bond that enabled donors to be matched with the recipients, former finance secretary Subhash Chandra Garg on Friday said the bank was not supposed to record the bond numbers and in doing so it had violated the anonymity promised to donors under the Electoral Bond Scheme, 2018. He also pointed out that the earlier affidavit filed by the bank on the matter was “ostensibly false”.
        The SBI had done something “completely unlawful and unexpected”, Garg told The Indian Express. By recording the alphanumeric codes of the bonds sold to donors and encashed by political parties, the bank had hit at the basic feature of the scheme that was brought in by the government in 2018 to enable anonymous political donations, he said.
        “The SBI said in its first affidavit that the information of donors and parties was kept in physical form in two silos and that it would take three months to match. But subsequent events have shown that they recorded the information in a digital form. Their first affidavit appears to be motivated by the desire to push the disclosure of the data beyond the Lok Sabha elections. Why did they file the ostensibly false affidavit,” asked Garg.`
    },
    {
        'id':5,
        'title':"BJP redeemed 81% of electoral bonds purchased by Nifty, Sensex companies",
        'image':"../../assets/images/samantha.png",
        'source':"Hindustan Times",
        "description":"Among the companies that bought electoral bonds starting April 2019, there are 15 listed in the Nifty 50 index, of whom eight are also listed in the BSE Sensex, as per the data published by the State Bank of India (SBI) and the Election Commission on Thursday. The 15 Nifty 50-listed companies account for total redeemed electoral bonds worth Rs 646 crore, while the Sensex-listed companies among them account for nearly half, that is Rs 337 crore. The BJP alone redeemed bonds worth Rs 521 crore bought by the 15 companies, or 81% of the total. The Nifty 50 represents an average of the 50 biggest companies listed on the National Stock Exchange. The Sensex is a similar index that represents 30 of the largest companies listed on the Bombay Stock Exchange. The companies on these indices represent key sectors across the Indian economy.",
        "detail_description": `Among the companies that bought electoral bonds starting April 2019, there are 15 listed in the Nifty 50 index, of whom eight are also listed in the BSE Sensex, as per the data published by the State Bank of India (SBI) and the Election Commission on Thursday.
        The 15 Nifty 50-listed companies account for total redeemed electoral bonds worth Rs 646 crore, while the Sensex-listed companies among them account for nearly half, that is Rs 337 crore. The BJP alone redeemed bonds worth Rs 521 crore bought by the 15 companies, or 81% of the total.
        The Nifty 50 represents an average of the 50 biggest companies listed on the National Stock Exchange. The Sensex is a similar index that represents 30 of the largest companies listed on the Bombay Stock Exchange. The companies on these indices represent key sectors across the Indian economy.`
    },
    {
        'id':6,
        'title':"GATE 2024 Toppers: From AIR 530 to rank 1, Piyush Kumar sets eye on IISc or IIT Bombay",
        'image':"../../assets/images/samantha.png",
        'source':"NDTV",
        "description":"GATE 2024 Toppers: Hailing from Uttar Pradesh, 21-year-old Piyush Kumar improved his Graduate Aptitude Test in Engineering (GATE) rank from 530 in 2023 to AIR 1 this year. His potion to success, he claims, was ensuring that all his concepts are clear. Kumar is a final year student of BTech CSE from Gurukul Kangri Vishwavidyalaya, Haridwar, Uttarakhand. He had been preparing for GATE for the past 15-16 months. When he appeared for GATE 2023, he hadn’t put in as much effort in preparation, so he decided to change his approach towards the exam this year. “I sat and looked back at what were the mistakes that I was making last year. I identified my weaknesses and worked harder in those areas. When I practised mock tests, I ensured that I did not miss out on those chapters which seemed difficult to me last year,” he told indianexpress.com.",
        "detail_description": `GATE 2024 Toppers: Hailing from Uttar Pradesh, 21-year-old Piyush Kumar improved his Graduate Aptitude Test in Engineering (GATE) rank from 530 in 2023 to AIR 1 this year. His potion to success, he claims, was ensuring that all his concepts are clear.
        Kumar is a final year student of BTech CSE from Gurukul Kangri Vishwavidyalaya, Haridwar, Uttarakhand. He had been preparing for GATE for the past 15-16 months. When he appeared for GATE 2023, he hadn’t put in as much effort in preparation, so he decided to change his approach towards the exam this year.
        “I sat and looked back at what were the mistakes that I was making last year. I identified my weaknesses and worked harder in those areas. When I practised mock tests, I ensured that I did not miss out on those chapters which seemed difficult to me last year,” he told indianexpress.com.`
    },
    {
        'id':7,
        'title':"Scientists find ‘Shiva’ and ‘Shakti,’ earliest building blocks of Milky Way",
        'image':"../../assets/images/samantha.png",
        'source':"Times Now",
        "description":"The Max Planck Institute for Astronomy on Thursday announced that astronomers have discovered what could be the earliest building blocks of the Milky Way, named “Shiva” and “ “Shakti. These seem to be the remnants of the two galaxies that merged between 12 and 13 billion years ago with an earlier version of the Milky Way, contributing to its growth. Astronomers from the institute named the components Shakti and Shiva and identified them after combining data from the European Space Agency’s Gaia satellite and the SDSS survey. This can be thought of like finding traces of an initial settlement that eventually grew into a metropolitan city, albeit on a cosmic scale. The collisions and mergers of galaxies put several things in motion. Each galaxy will carry its own reservoir of hydrogen gas and when colliding, these clouds are de-stabilised and many new stars will be formed inside. Of course, both the galaxies will have their own sets of stars before they collide and these “accreted stars” will only account for some of the stellar population that forms the newly-combined galaxy. The tricky part is identifying which stars came from which predecessor galaxy when the merger is done.",
        "detail_description": `The Max Planck Institute for Astronomy on Thursday announced that astronomers have discovered what could be the earliest building blocks of the Milky Way, named “Shiva” and “ “Shakti. These seem to be the remnants of the two galaxies that merged between 12 and 13 billion years ago with an earlier version of the Milky Way, contributing to its growth.
        Astronomers from the institute named the components Shakti and Shiva and identified them after combining data from the European Space Agency’s Gaia satellite and the SDSS survey. This can be thought of like finding traces of an initial settlement that eventually grew into a metropolitan city, albeit on a cosmic scale.
        The collisions and mergers of galaxies put several things in motion. Each galaxy will carry its own reservoir of hydrogen gas and when colliding, these clouds are de-stabilised and many new stars will be formed inside. Of course, both the galaxies will have their own sets of stars before they collide and these “accreted stars” will only account for some of the stellar population that forms the newly-combined galaxy. The tricky part is identifying which stars came from which predecessor galaxy when the merger is done.`
    },
    {
        'id':8,
        'title':"UN Security Council fails to pass US resolution calling for immediate ceasefire in Gaza",
        'image':"../../assets/images/samantha.png",
        'source':"The Independent",
        "description":"The United Nations Security Council on Friday failed to pass a resolution calling for an immediate ceasefire in Gaza as part of a hostage deal after Russia and China vetoed the measure proposed by the United States. The resolution, which Guyana also abstained from voting for, called for an immediate and sustained ceasefire lasting roughly six weeks that would protect civilians and allow for the delivery of humanitarian assistance. It marked a further toughening of Washington’s stance toward Israel. Earlier in the five-month-long war, the U.S. was averse to the word ceasefire and vetoed measures that included calls for an immediate ceasefire.",
        "detail_description": `The United Nations Security Council on Friday failed to pass a resolution calling for an immediate ceasefire in Gaza as part of a hostage deal after Russia and China vetoed the measure proposed by the United States.
        The resolution, which Guyana also abstained from voting for, called for an immediate and sustained ceasefire lasting roughly six weeks that would protect civilians and allow for the delivery of humanitarian assistance.
        It marked a further toughening of Washington’s stance toward Israel. Earlier in the five-month-long war, the U.S. was averse to the word ceasefire and vetoed measures that included calls for an immediate ceasefire.`
    },
    {
        'id':9,
        'title':"DGCA slaps Rs 80 lakh fine on Air India for violating pilot fatigue-related rules",
        'image':"../../assets/images/samantha.png",
        'source':"Hindustan Times",
        "description":"Aviation safety regulator Directorate General of Civil Aviation (DGCA) on Friday slapped Air India with a Rs 80-lakh fine for violation of rules relating to flight duty time limitations (FDTL) and fatigue management system (FMS) for pilots. These sets of rules are in place to prevent crew fatigue, which can be dangerous for flight operations apart from having a negative impact on the health of the crew. The regulator’s action follows a January spot audit of the Tata group’s flagship airline to ascertain its compliance with the FDTL and FMS regulations. “The analysis of reports and evidences revealed that M/s Air India Limited operated flight(s) with both flight crew aged above 60 years flying together in few instances, which is a violation of Sub Rule (2) of Rule 28 A of the Aircraft Rules, 1937,” the DGCA said in a statement.",
        "detail_description": `Aviation safety regulator Directorate General of Civil Aviation (DGCA) on Friday slapped Air India with a Rs 80-lakh fine for violation of rules relating to flight duty time limitations (FDTL) and fatigue management system (FMS) for pilots. These sets of rules are in place to prevent crew fatigue, which can be dangerous for flight operations apart from having a negative impact on the health of the crew.
        The regulator’s action follows a January spot audit of the Tata group’s flagship airline to ascertain its compliance with the FDTL and FMS regulations.
        “The analysis of reports and evidences revealed that M/s Air India Limited operated flight(s) with both flight crew aged above 60 years flying together in few instances, which is a violation of Sub Rule (2) of Rule 28 A of the Aircraft Rules, 1937,” the DGCA said in a statement.`
    },
    {
        'id':10,
        'title':"Samantha Ruth Prabu ‘passed out’ from a head concussion while shooting due to Myositis — an autoimmune condition",
        'image':"../../assets/images/samantha.png",
        'source':"Times Now",
        "description":"Samantha Ruth Prabhu opened up about fainting while shooting an action sequence for a film after her diagnosis with the autoimmune condition, Myositis. Talking about the incident on her new health podcast series Take 20, the actor recounted the incident, saying, “I passed out. I had a head concussion.” The 36-year-old was in conversation with wellness coach and nutritionist Alkesh Sharotri, in the latest episode of her health podcast series. She discussed in detail her experience with Myositis; beginning with how she dealt with the diagnosis and her current health status. For the uninitiated, Samantha first opened up about her diagnosis back in 2022, sharing a post on Instagram. “A few months back I was diagnosed with an autoimmune condition called myositis. I was hoping to share this after it had gone into remission. But it is taking a little longer than I hoped,” she captioned the post.",
        "detail_description": `Samantha Ruth Prabhu opened up about fainting while shooting an action sequence for a film after her diagnosis with the autoimmune condition, Myositis. Talking about the incident on her new health podcast series Take 20, the actor recounted the incident, saying, “I passed out. I had a head concussion.”
        The 36-year-old was in conversation with wellness coach and nutritionist Alkesh Sharotri, in the latest episode of her health podcast series. She discussed in detail her experience with Myositis; beginning with how she dealt with the diagnosis and her current health status.
        For the uninitiated, Samantha first opened up about her diagnosis back in 2022, sharing a post on Instagram. “A few months back I was diagnosed with an autoimmune condition called myositis. I was hoping to share this after it had gone into remission. But it is taking a little longer than I hoped,” she captioned the post.`
    }
]