export const USER_DATA = 'USER_DATA';
export const ADMIN_JAINS_KART = 'ADMIN_JAINS_KART';
export const CART_COUNT = 'CART_COUNT';
export const CART_DATA = 'CART_DATA';
export const JAINS_KART_ALL_DATA = 'JAINS_KART_ALL_DATA';
export const JAINS_KART_SELECTED_PRODUCT = 'JAINS_KART_SELECTED_PRODUCT';